### ISSUE TITLE
Linux 64-bit binaries zip inflates many files into the current directory

### ISSUE THREAD

**Issue by dhasenan** [BBasile/Coedit#11]
On Linux, when distributing archives, it's considered polite to provide a single root directory containing other files (unless the archive contains only one file). This is because unzip, tar, etc default to extracting the entire contents of an archive in the current directory rather than creating a new directory for the archive's contents.

Coedit's linux-64 binary download (and perhaps others) extracts multiple files into the current directory. This is mildly annoying.

**Comment by BBasile** [comment]
This is faisable. (in https://github.com/BBasile/Coedit/blob/master/cesetup/zip-nux64.sh).
The zip was actually more dedicated to experienced user who wants to put themselves the bin here or there, the logo in a place to another and not to work like a tarball with a decompression that respects the file system organization.
