### ISSUE TITLE
Editor font size configuration seems to be ignored

### ISSUE THREAD

**Issue by dhasenan** [BBasile/Coedit#12]
Testing "latest download" as of about 7 February 2016 at 16:45 UTC. Windows -> About lists it as Coedit 2 rc 1.

I am able to change the font, but the font size seems to be ignored. I switched from Courier New to Droid Sans Mono, and the font changed appearance, but switching from Droid Sans Mono 10pt to Droid Sans Mono 24pt did not produce any change. Also tried with FreeMono and Courier New.

**Comment by BBasile** [comment]
The current behavior is so:

if you create a new editor after changing the font size, the new editor font has the correct size.
To reflect the change on the current editor press <kbd>CTRL<kbd>+<kbd>.<kbd> (or Ctrl + middle mouse bouton).

What happens now is that an editor that has the default font size is not updated.

**Comment by BBasile** [comment]
version 2 will have an option that, when activated, ignore the current cutom zoom level of the font, so that each editor will get the new "default size" without the need to make an explicit reset.
