### ISSUE TITLE
Wrong installation path using coedit.2gold.linux64.setup on Ubuntu 15.10

### ISSUE THREAD

**Issue by fbis251** [BBasile/Coedit#13]
`coedit.2gold.linux64.setup` installed the coedit binaries under the wrong path (for example: `/usr/bincoedit` instead of `/usr/bin/coedit`)

     $ sudo ./coedit.2gold.linux64.setup 
    +--------------------------------------------------+
    |              Coedit 2 gold - setup               |
    +--------------------------------------------------+
    | Coedit will be accessible to all the users       |
    +--------------------------------------------------+
    | options:                                         |
    |                                                  |
    | -l | --list: list files and status               |
    | --nodcd: skip DCD setup                          |
    | -u | --uninstall: uninstall                      |
    | press A to abort or another key to start...      |
    +--------------------------------------------------+

    +--------------------------------------------------+
    | coedit: extracted                                |
    | cesyms: extracted                                |
    | cetodo: extracted                                |
    | coedit.ico: extracted                            |
    | coedit.png: extracted                            |
    | coedit.license.txt: extracted                    |
    | dcd-server: extracted                            |
    | dcd-client: extracted                            |
    | dcd.license.txt: extracted                       |
    +--------------------------------------------------+
    | the files are correctly extracted...             |
    |                                                  |
    |                           ...press a key to exit |
    +--------------------------------------------------+

     $ sudo ./coedit.2gold.linux64.setup -l
    +--------------------------------------------------+
    +--------------------------------------------------+
    |              files list and status               |
    +--------------------------------------------------+
    /usr/bincoedit installed: true
    /usr/bincesyms installed: true
    /usr/bincetodo installed: true
    /home/user/.config/Coedit/coedit.ico installed: true
    /home/user/.config/Coedit/coedit.png installed: true
    /home/user/.config/Coedit/coedit.license.txt installed: true
    /usr/bindcd-server installed: true
    /usr/bindcd-client installed: true
    /home/user/.config/Coedit/dcd.license.txt installed: true
    +--------------------------------------------------+

    $ file /usr/bincoedit
    /usr/bincoedit: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.4.0, stripped
    $ file /usr/bin/coedit
    /usr/bin/coedit: cannot open `/usr/bin/coedit' (No such file or directory)

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 15.10
    Release:        15.10
    Codename:       wily

**Comment by BBasile** [comment]
confirmed, only sudo setup is affected.

**Comment by BBasile** [comment]
setup.linux64 updated. Thx for the report.
