### ISSUE TITLE
Under Ubuntu, no GUI shown, but no error

### ISSUE THREAD

**Issue by EmTee70** [BBasile/Coedit#148]
Hello, I tried to install on Ubuntu LTE 14.04. 64 Bit, with setup program.
After start the process is running but no visible output.
Top:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     ZEIT+ BEFEHL
 9983 mt        20   0  476808 349964   9740 R  99,7  2,1  10:13.85 coedit 
Is there anything I can do get an more informative error message to help?
( I don't want to build it...)

**Comment by BBasile** [comment]
In a firs time launch it from a terminal. Maybe there'll be something interesting. If no i can provide you a debug build.

> no visible output.

I assume you mean the GUI ? The program runs but the UI is not visible ? 
Do you have gtk2 runtime libraries well setup ?

**Comment by BBasile** [comment]
I also suspect that this is caused by the compiler detection.The first time the software is run it always hang a bit. This would also explain the 99.7% usage of the CPU.

**Comment by EmTee70** [comment]
Hiho, 
I did an sudo apt-get install gtk2.0 
but still the same: no output, neither terminal nor desktop. After 2:45 Minutes CPU-Time.

**Comment by BBasile** [comment]
I'd like you to try something: create a file named `compilerpaths.txt` 
in `/home/<your account name>/.config/Coedit/` with the following content

```
object TCompilersPaths
  defaultCompiler = dmd
  DmdExeName = '/usr/bin/dmd'
  DmdRuntimePath = '/usr/include/dmd/druntime/import'
  DmdPhobosPath = '/usr/include/dmd/phobos'
end
```

Don't forget to change the filename and the two paths if they don't match. This will allow to verify if the culprit is the compiler detection. By the way what is the dmd version ?

**Comment by BBasile** [comment]
Here is a [special build](https://github.com/BBasile/Coedit/releases/download/3_update_1/coedit_dbg_init.zip) that you can launch from a terminal. Copy & paste the terminal content.
DWARF info are generated so it's also possible to run it in GDB.

**Comment by EmTee70** [comment]
DMD64 D Compiler v2.074.0
Copyright (c) 1999-2017 by Digital Mars written by Walter Bright

```
mt@spm8c:~/.config/Coedit$ which dmd
/usr/bin/dmd
locate include/dmd/druntime/import/ 
```
delivers=> 
```
/usr/include/dmd/druntime/import....
```

With "normal" version no output.
Now trying special build.

**Comment by BBasile** [comment]
Did you make a sudo setup ?

**Comment by EmTee70** [comment]
No. No sudo setup, should I try?

**Comment by BBasile** [comment]
It depends. can you launch coedit by typing its name, i.e when you're not in its directory ? 
For the user only setup i use `/home/bin/` but i'm not sure if all the distribs add it automatically to the PATH.

But otherwise, any log output from the debug version ?

**Comment by EmTee70** [comment]
```
mt@spm8c:~$ which coedit
/home/mt/bin/coedit
mt@spm8c:~$ ls -l `which coedit`
-rwxr-xr-x 1 mt mt 46344696 Mai 23 19:55 /home/mt/bin/coedit
```
But no output to the terminal, is coedit writing a log file?

**Comment by EmTee70** [comment]
My estimation is, that our distro LTS 14.04 is to old, I will try it again after an update to 16.04.
May be in the next week.

**Comment by BBasile** [comment]
> But no output to the terminal, is coedit writing a log file?

No it writes in stdout.

> My estimation is, that our distro LTS 14.04 is to old

Trying at work ? Maybe something special about your network / filesystem ?

**Comment by EmTee70** [comment]
We have a LTSP linux terminal sever environment with (up to 5) small WYSE  thin clients on the desktop and just one 8 core 12 GB ram server. So all apps are running on the server and are displayed on a X11.terminal. And the thin clients are booting via LAN. No disks. So one dist-upgrade for all...

**Comment by BBasile** [comment]
I'm not sure if the OS upgrade will help, TBH i'm not competent here. I know that it works fine on single post computers but i'm unaware of the tricky details that seem to happen here (and i'm no able to reproduce them from my side).

**Comment by BBasile** [comment]
It looks like the problem cant be really identified or reproduced. Support thread finishes here then.

**Comment by BBasile** [comment]
While Discussing on IRC it has appeared that another person, "Dejan", has encountered exactly the same problem. On Ubuntu too.

**Comment by BBasile** [comment]
@EmTee70, if you have a few minutes, can you read #210, and tell me if the the custom file as described [here](https://github.com/BBasile/Coedit/issues/210#issuecomment-350742160) also fix this issue ? I suspect that it's the same.

**Comment by EmTee70** [comment]
I will do so, but maybe it works now, because I have updated the system to 16.04. at my desk and and 17.10 at home.

**Comment by BBasile** [comment]
Okay, you don't need to test, i'm 99% sure that it was the same issue. Last spring, when i asked you to create a special file i forgot some sections. Without them the bug was still triggered. Sadly I've only realized that error yesterday.

**Comment by EmTee70** [comment]
For your info only, just tried out Coedit and it works on Ubuntu 16.04.
