### ISSUE TITLE
Rename coedit to...

### ISSUE THREAD

**Issue by BBasile** [BBasile/Coedit#149]
It's time to get rid of this stupid name. Opened to suggestion :wink:

**Comment by agauniyal** [comment]
DIDE 😂

**Comment by BBasile** [comment]
already exists. Actually i thought to `drwx--` which is inspted by file rights on unix expected that here it would mean "read write execute D".

**Comment by agauniyal** [comment]
drwx would be a little hard to pronounce. How about deagle?
