### ISSUE TITLE
Q CoEdit should not gratuitously create a directory under $HOME for storing preferences

### ISSUE THREAD

**Issue by jamadagni** [BBasile/Coedit#15]
Hello. I find CoEdit very nice for my interest in D. But every time I run it it creates a directory by name Coedit under my home folder for storing its preferences. I would expect that like all other apps that run on my Linux box, it should store these under an invisible directory (i.e. with naming starting with a dot/period) under $HOME and not a visible one.

I understand that Coedit is cross-platform, but I presume Windows also has its own dedicated location for such App-specific settings folders (User/<username>/AppData or something, I'm not sure) rather than the Home directory of the user.

Until you fix the default installation to use such a hidden directory, please at least tell me how to make it so that I am able to move these preferences to a hidden directory and have Coedit recognize it.

Thanks!

**Comment by BBasile** [comment]
it's set visible on purpose. 
The folder contains some data that can be modified by the user 
- editor cache.
- settings that are not editable like MRU file count.
- docking problem can be solved by deleting docking.xml
- most of the settings files are editable by hand.

This won't change in version 1.

**Comment by jamadagni** [comment]
It's fine if it won't change in version 1 if you have no time to fix it or such, but don't close it just because of that.

Lots of config files under ~/.config etc are modifiable by the user in Linux. Doesn't need the directory to be visible for just for that. Intermediate (if not novice) users of Linux are aware about such hidden directories.

**Comment by jamadagni** [comment]
Heh. The offending code is on line 531 of src/ce_common.pas: `result := getUserDocPath + 'Coedit' + directorySeparator;` but since I didn't have the patience to install all the varied dependencies and compile from scratch, I resorted to "underhanded hacking"! ;-)

On my 64-bit Linux system I merely opened up /usr/bin/coedit and among multiple instances of the string "Coedit" I found the one near ~/ (actually it is easier to find it by searching for %.8X as it is just before that) and overwriting "Coedit" with ".coedi" -- recalling to my mind one of my earliest trips into "dangerous" editing of user-visible strings in installed executables I learnt almost 20 years ago as a kid! :-) One limitation: I can only use 6 chars in the replacement string... Ah well. :-)

**Comment by BBasile** [comment]
Come on, be reasonable. 

This is just a folder that's shown. You'd prefer a software that creates things that are not shown and one day by manipulating your file system you discover several megs of garbages ?

**Comment by jamadagni** [comment]
I have enough trust in you that I am sure the Coedit program does not write "several megs of garbages". As to preferring "software that creates things that are not shown" -- for comparison on my Kubuntu Trusty LTS system the following software currently use the following amounts of disk space (as reported by du -hsc) to store their preferences and related data all under hidden directories under my $HOME directory:

1) the very popular SVG editor Inkscape (v0.91 latest trunk): 26587 *bytes* as ~/.config/inkscape/preferences.xml

2) the very popular raster image editor GIMP (2.8.10 recent version): 600 K under ~/.gimp-2.8/

3) the very popular office suite LibreOffice (4.4.3 latest): 3.8 MB under ~/.config/libreoffice/

4) the very popular (among *nix OSs) desktop environment KDE (4.13.3 recent version): 29 M under ~/.kde

I have now and then entered these directories to directly edit settings and have never had a problem with them being supposedly "hidden". It leaves my home directory clean and uncluttered for the files I actually create.

So I guess I'm being entirely reasonable. Is there any other problem with using a hidden directory in terms of just using an initial dot for the directory name?

I have just sent you a pull request. I did clone/fork/everything just for this one line. So I hope everyone can be reasonable!

**Comment by BBasile** [comment]
marked for next major release
