### ISSUE TITLE
Code completion doesn't automatically close after deleting

### ISSUE THREAD

**Issue by shad1w** [BBasile/Coedit#152]
When code completion is active, it doesn't automatically close when the text to be completed is deleted again.

Without closing code completion manually before, this results in two bugs mainly:
- When another word is entered, that starts with another letter, completions will not be available as the list used for the previous word is still entered.
- It's not possible to delete anything before the position at which code completion has been activated at.

**Comment by BBasile** [comment]
until done: <kbd>ESC</kbd> before supression.
