### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by BBasile** [BBasile/Coedit#16]
If you encounter problems while [building CE under OSX](https://github.com/BBasile/Coedit/wiki#build-the-sources) you can post a message here with  screenshots, stacktrace, anything that can help.

**Comment by BBasile** [comment]
Carbon i386 is OK: https://travis-ci.org/BBasile/Coedit/builds/110387890
Since OSX support is  bit Laz's poor child, I'd say this is the most you can get.
Buidling another widget set might be a problem. 

- IIRC @btbytes tried Qt a few monthes ago. Don't do this, this is the hardest option !
- cocoa is not ready yet: http://forum.lazarus.freepascal.org/index.php/topic,29732.0.html

**Comment by BBasile** [comment]
@dossan , CE  for OSX, things happen here now.

**Comment by Imagix** [comment]
So far compiling has been succeeding, but when you actually try to run it, it appears to flash up a bunch of the windows and then segfaults.  Attached, output.txt is the console output when running the executable directly, and problem.txt is the output of the problem report when it's run as an OSX application and the dialog pops up about reporting the problem to Apple (this contains a stack trace...)

[output.txt](https://github.com/BBasile/Coedit/files/152972/output.txt)
[problem.txt](https://github.com/BBasile/Coedit/files/152973/problem.txt)

**Comment by BBasile** [comment]
Thx. One first thing, the most simple is what mono font name should I use by default for OSX ?

> CarbonFontIDToFontName Error: ATSUFindFontName Length failed with result -8905
