### ISSUE TITLE
Add option to specify additional exe search paths

### ISSUE THREAD

**Issue by vakosel** [BBasile/Coedit#19]
How can i use the dfmt from the interface? I have it on my path and works fine from the command line.
But when i use the commander nothing happens . Os : Archlinux

Thanks in advance

**Comment by BBasile** [comment]
Does it appears yellow in the _About_ window ?

![](http://i.imgur.com/0XgMeDs.png)

If so then it's not detected.

**Comment by BBasile** [comment]
Otherwise when a document is opened, click the green icon to apply. It is only applied to current doc.

**Comment by vakosel** [comment]
the problem was that actually. Couldn't see .local/bin even though it is on my path variable. 
Copied to /usr/bin and everything working nice. Maybe if there is an option to the location of the executables would be fine?
Thanks again for helping me!

**Comment by BBasile** [comment]
I'll add an option to modify CE environment but I'd like to know.

Are you sure that the folder where resides _dfmt_ is included in the list you get when `echo $PATH` ? for example does `which dfmt` succeed ?

**Comment by BBasile** [comment]
implementation guide:

- add a string to the application option (e.g `property additionalPath: string read ...`).
- store reload from/to a global in _ce_common.pas_.
- use this global in the function _exeFullName_ and _exeInSysPath_.
- additional check: verify that all the TProcess / TCEProcess / ... use _exeFullName_.
