### ISSUE TITLE
"Reset layout" option

### ISSUE THREAD

**Issue by dmi7ry** [BBasile/Coedit#191]
Sometime docking works very strange - it may lose windows, etc (and then is not possible to see the lost window). And even if I saved default layout and then load it, it may work wrong.

Add "default" option which will reset the layout into default state, please.

**Comment by BBasile** [comment]
Easy addition, in the meantime you can delete the option file (close coedit, delete docking.xml and launch coedit again). Also once you're happy with the layout, don't forget to lock it (right click on any widget header to see the option).

**Comment by dmi7ry** [comment]
>  you can delete the option file (close coedit, delete docking.xml and launch coedit again)
That is what I already did many times.

>  (right click on any widget header to see the option).
oh, thank you.
