### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by kaluosi** [BBasile/Coedit#2]
What you write in your "Setup Section" has no relation at all with the content you have in your repository. Where are the different binaries for different platform. In https://github.com/BBasile/Coedit/release there is only code. Should we install Free Pascal and compile the sources. I can't see any other way.

**Comment by BBasile** [comment]
It's the same as #1. I'll publish a release in the next hours (2_alpha_3), just a few things to check and it's back. I've explained this previously but CE's been removed then republished, so the previous releases with the binaries, the notes, are lost.

**Comment by BBasile** [comment]
[A new release is availalbe](https://github.com/BBasile/Coedit/releases/tag/2_alpha_3), with setup program and pre build binaries.

**Comment by kaluosi** [comment]
OK. Initially it works.It looks promising. What curious, an IDE for D programming made in Free Pascal. Great work!!
