### ISSUE TITLE
Add dependencies requirement to the rpm

### ISSUE THREAD

**Issue by BBasile** [BBasile/Coedit#215]
also maybe for the setup program

**Comment by BBasile** [comment]
Actually the deb and the rpm are the only linux package i ever made so if someone has more experience with that, the deb control file and the rpm spec are respecectively generated [here](https://github.com/BBasile/Coedit/blob/master/cesetup/deb.sh) and [here](https://github.com/BBasile/Coedit/blob/master/cesetup/rpm.sh).

**Comment by Nafees10** [comment]
using `ldd coedit` (coedit is the Coedit executable), and `dpkg -S libname`, I got this list of dependencies:
```
libc6
libgtk2.0-0
libgdk-pixbuf2.0-0
libglib2.0-0
libpango-1.0-0
libcairo2
libatk1.0-0
libpangocairo-1.0-0
libglib2.0-0
libfontconfig1
libxrender1
libxinerama1
libxi6
libxrandr2
libxcursor1
libxcomposite1
libxdamage1
libxfixes3
libxext6
libxcb1
libpangoft2-1.0-0
libffi6
libpcre3
libthai0
libpixman-1-0
libfreetype6
libpng16-16
libxcb-shm0
libxcb-render0
zlib1g
libselinux1
libmount1
libexpat1
libxau6
libxdmcp6
libharfbuzz0b
libdatrie1
libblkid1
libbsd0
libgraphite2-3
libuuid1
```
These are for ubuntu (xubuntu to be specific) 17.10.

**Comment by BBasile** [comment]
After checking the rpm build log it appears that RPM deps were added automatically.
Added generic package names anyway.
