### ISSUE TITLE
Uninstaller?

### ISSUE THREAD

**Issue by lainz** [BBasile/Coedit#222]
Hi, I installed this program only for helping with the High DPI problems. When I want to uninstall it there is no such uninstaller.

You can make one?

I use Inno Setup, is made with Delphi, and is a industry standard, used for example by Visual Studio Code to bundle his setup.

Thanks.

Edit: If you use Linux only and not Windows, you can try to use a virtual machine or just Wine, then install Inno Setup.-

**Comment by lainz** [comment]
I found the uninstaller, but here in the Windows world we use the uninstall tool that comes with Windows.

**Comment by BBasile** [comment]
Yeah, you must run the setup program with -u. The reason why i do that is because i can compile the installer/uninstaller for all the platforms using the same project.

Actually contrary to what you think I did many inno setup installers in the past (< 2012) ;)
