### ISSUE TITLE
Need check

### ISSUE THREAD

**Issue by Alexey-T** [BBasile/Coedit#238]
```
function TCESynMemo.lineTextAtCarret(): string;
+begin
+  Result := Strings.LinesUTF8[Carets[0].PosY];
+end;
```
sometimes caret is out of text. Need chk 

var Caret: TATCaretItem;
Caret:= Carets[0];
if Strings.IsIndexValid(Caret.PosY) then ...

**Comment by BBasile** [comment]
You can make PR against the branch made for the conversion.
I can invite you so that you can report problems or add cards to the project.

**Comment by BBasile** [comment]
I use GH issues for the changelog, it's better to change the project for the details.
