### ISSUE TITLE
Add autoupdate

### ISSUE THREAD

**Issue by arietto** [BBasile/Coedit#243]
Please, add autoupdate functionality in About window. Or at least, add Check for updates  in About window.
Also,  tooltip can be added: "New version is available".

**Comment by BBasile** [comment]
There's an option for this: Options -> Application -> autoCheckUpdates.
Unfortuantely it's victim of a bug in the library i use so it might only work in some cases...

**Comment by BBasile** [comment]
It's possible to add a button  somewhere to trigger it manually
