### ISSUE TITLE
Adding compiler name to log 

### ISSUE THREAD

**Issue by arietto** [BBasile/Coedit#246]
I see the following message in the log window:
compiling C:\...\Temp\temp_042109F0.d
. I think that it would be helpful to see the compiler name:
"Using ldc compiler.
Compiling C:\...\Temp\temp_042109F0.d"

**Comment by BBasile** [comment]
Why not. The compiler used is set in the options for the runnables but it's easy to forget which one you use.
THe string would be more are translation of the option, e.g if "user1" is "dmd-git545454bla" then "user1" would be displayed.
