### ISSUE TITLE
hello im beginer and i have trouble on installing and initiating

### ISSUE THREAD

**Issue by KimSH1238** [BBasile/Coedit#249]
i saw tutorial of coedit but i cant install and start.
i dont know how to do and i installed in external ssd so my folder is different than others.

i reeeeallly cant start with text guide. and i dont know what i open and what to do.

if u can take screenshot or simple video, please post up. i have truoble

**Comment by BBasile** [comment]
Coedit first five minutes in video. https://www.youtube.com/watch?v=46f7dlnmLGs&index=1&t=0s&list=PLzk8A0LUvEOV-OMdz09jfOahwnKoA2na_

**Comment by KimSH1238** [comment]
i am very thank u to upload detail video.

now im far from laptap i use but tomorrow i will try.

at now im using win7 but im trying to do many os installaing linux ubuntu.

after i success, i can imitate installing.

very thank u !
