### ISSUE TITLE
mac osx support

### ISSUE THREAD

**Issue by Extrawurst** [BBasile/Coedit#279]
will there ever be a mac version provided? AFAIK lazarus supports mac os, right?

**Comment by BBasile** [comment]
Yes Laz support osx but first i don't have the hardware to make it, second nobody has ever took the time to work seriously on the port, although most of the code is already compatible.

**Comment by BBasile** [comment]
In the past i did use TravisCI but having the soft to compile is something else than having it to run for hours without issue.

BTW anyone can volunteer for the Mac OS version.

**Comment by Extrawurst** [comment]
sure
