### ISSUE TITLE
Cannot save files

### ISSUE THREAD

**Issue by takase1121** [BBasile/Coedit#288]
I tried to save a file and it says "no write access in (directory) ". I tried to launch the program in admin mode and moved it to the desktop but that didn't solve the problem. Any ideas?

**Comment by BBasile** [comment]
I need more info: OS, OS version, the way you use to get Coedit (zip, setup program, 3rd part ?).
In the meantime i've made a video recently showing how to setup using the zip under linux: https://www.youtube.com/watch?v=46f7dlnmLGs&list=PLzk8A0LUvEOV-OMdz09jfOahwnKoA2na_&index=2&t=0s

**Comment by takase1121** [comment]
I am using windows 8.1 bing and I got coedit from the setup program.

**Comment by BBasile** [comment]
It must something on your system. CE is almost 4 years old now. I used it much on win at the beginning and occasionally still do, like yesterday where i could save several files without problems. Also i never had any similar reports from Windows users.

You can ask more help if you like but i don't consider this as a bug (and i close).
Do the same files can be saved in another editor, let's say NP++ for example ?

**Comment by takase1121** [comment]
Yes they can but coedit can't
