### ISSUE TITLE
Better settings text 

### ISSUE THREAD

**Issue by takase1121** [BBasile/Coedit#290]
Sometimes the settings panel can be hard to understand. The settings looked like something that directly came from the config file.

**Comment by BBasile** [comment]
This is deliberately done like that. Unless someone wants to program the UI frame for each category i'll always mostly use an RTTI-based property inspector. I admit this is not easy on the eyes but it's really fast to make and saved hundreds of line of code. Pass an object to the editor and all the properties are automatically binded. This is also why there's no spaces in the properties. They are actually identifiers.

**Comment by takase1121** [comment]
I see. Thank you!
