### ISSUE TITLE
Question on Library Manager

### ISSUE THREAD

**Issue by DLDavid** [BBasile/Coedit#296]
when creating the runnable module using the library manager, I keep getting this error message
error, failed to compile the package to register

I tried the urld, and the yatol and both gave the same error.
What am I doing incorrectly?

Thanks...

**Comment by BBasile** [comment]
i managed to setup urld with the DUB button just now. What is the Coedit version ?

**Comment by BBasile** [comment]
It's possible that the website was sown when you have tried. In this case it's still possible to setup a library when it's opened as a project, using the ![](https://github.com/BBasile/Coedit/blob/master/icons/book/book_link32.png?raw=true) icon

**Comment by DLDavid** [comment]
Problem still persists. 
I have tried to add several libraries which are added to the directory, but it cannot compile them. Is there a permissions issue? Currently running the latest version 3.6.5. Understand I am new to this ide and using it in runnable mode.

<img width="1370" alt="screen shot 2018-04-15 at 9 25 28 pm" src="https://user-images.githubusercontent.com/13157351/38787647-e695b840-411e-11e8-9d8e-e6250d695286.png">

**Comment by BBasile** [comment]
- what is your distro ?
- windows -> About screenshot ?
- `$ which dub`

**Comment by BBasile** [comment]
Alos if you use the command `$ dub fetch dsymbol` in a console, does it work (so independantly from the IDE)?

**Comment by DLDavid** [comment]
I am running on a macbook in parallels I also noticed I cannot close the application as well. I think this is a permission issue but not sure where to look.
<img width="857" alt="screen shot 2018-04-16 at 7 19 45 am" src="https://user-images.githubuse
<img width="870" alt="screen shot 2018-04-16 at 7 28 11 am" src="https://user-images.githubusercontent.com/13157351/38809367-db99d9a6-4148-11e8-8c25-e00bd566f052.png">
<img width="729" alt="screen shot 2018-04-16 at 7 25 50 am" src="https://user-images.githubusercontent.com/13157351/38809368-dbb6c70a-4148-11e8-8bde-4379ca681a5e.png">
<img width="365" alt="screen shot 2018-04-16 at 7 21 28 am" src="https://user-images.githubusercontent.com/13157351/38809369-dbd31a9a-4148-11e8-8ad7-3395a4837549.png">


rcontent.com/13157351/38809338-cd41ab0e-4148-11e8-9f88-f61836ecd6ce.png">

**Comment by DLDavid** [comment]
Sorry here is the distro
<img width="857" alt="screen shot 2018-04-16 at 7 19 45 am" src="https://user-images.githubusercontent.com/13157351/38809428-11985474-4149-11e8-9f97-2ef58444d9fe.png">

**Comment by BBasile** [comment]
Might be a _parallels_ problem too. I just discover this thing exists. To be perfectly clear, your run Coedit for Windows on a mac using _Parallels_ ?

**Comment by BBasile** [comment]
What are the permissions for `/home/parallels/.config/Coedit` ?

**Comment by DLDavid** [comment]
Here are the permissions for the .config folder.
<img width="738" alt="screen shot 2018-04-16 at 9 15 23 am" src="https://user-images.githubusercontent.com/13157351/38814243-a80bd720-4156-11e8-8dff-75edd9c4c293.png">

**Comment by BBasile** [comment]
The problem is clear. You must set the permission from root to parallels. There's a demo here https://www.youtube.com/watch?v=wyKxOC2YOrU, the guy is not a Formula1 of typing but this is what you have to do (you can also probably add more permissions instead of changing ownership)

**Comment by DLDavid** [comment]
OK successfully recreated the directory with the correct permissions and can save config. Still having the same issue with the "Library Manager". 
Do you think this is the same issue should I uninstall and reinstall? I used the same login to install cannot remember if I used sudo to do the install thought.

**Comment by BBasile** [comment]
Maybe it's the same issue. Look at the permission of the binary (if you have setup with sudo then it's certainly in `/user/bin/`). I usually recommend to use `~/bin/` when extracting from the zip or not using sudo when using the setup program.

**Comment by DLDavid** [comment]
I will reinstall it locally this will eliminate the permission issues from the problem. 
Thanks will confirm if it works

**Comment by DLDavid** [comment]
Installing it locally cleared the problems. It was permissions that were causing the problems. 
I am good to go... Thanks...
