### ISSUE TITLE
Strange behavior when saving files

### ISSUE THREAD

**Issue by takase1121** [BBasile/Coedit#297]
Sorry for opening a new issue, but I observed a really interesting behavior of Coedit.

When you try to save the file to Desktop directly, the program will throw an error.

However, when you save the file to a folder in Desktop, the error won't happen and it saves correctly.

This behavior is also observed on the items on the left side of the save dialog, but only applies to Desktop, Documents, Downloads, Pictures and Musics tab(I only test those tabs).
 
See the picture for more details.
![image](https://user-images.githubusercontent.com/20792268/38805873-0ae1e8d2-41aa-11e8-951a-39c91e7e4d6b.png)

![2018-04-16 18_58_41-coedit](https://user-images.githubusercontent.com/20792268/38805655-33ca479a-41a9-11e8-97fd-5fab8eb84e3a.png)
![2018-04-16 18_58_16-coedit](https://user-images.githubusercontent.com/20792268/38805657-341e80ee-41a9-11e8-8627-ea4938bd7244.png)

**Comment by BBasile** [comment]
Yes i can see that on windows 7.1 too.

**Comment by BBasile** [comment]
Actually if you check the attributes in the windows context menu these folders are well marked read-only.
For now i'll simply check if the file is read only instead of checking its location.

**Comment by takase1121** [comment]
I see. Thanks!
