### ISSUE TITLE
Opening the terminal in Linux gives an "Access Violation" 

### ISSUE THREAD

**Issue by leh103** [BBasile/Coedit#298]
I have installed Coedit-3.6.7 using the linux64.setup file on both the Zorin OS and the Debian based version of Mint LInux lmde2. I get an "Access Violation" when ever I open the the Terminal window via both the menu and by clicking on the tab. And, I get no prompt in the Terminal. The default Terminal emulator on both is the Gnome-Terminal.

On I think a related issue, when installing from the linux64.deb file it appears to install correctly, but crashes when open with an abort error message.

This really is not that important as I can just open the Terminal from the file manager and use it, but I thought you'd like to know.

**Comment by BBasile** [comment]
Actually my statement about the library required might be wrong since gnome-terminal may use the version for GTK3. Coedit requires VTE for GTK2. Do you have _libvte.so_ in the _/usr/lib64_ ?

Beside, no Access violation should happen anyway.

**Comment by BBasile** [comment]
damn It's just a stupid access to the shared library when it hasn't be loaded. I'm 99% sure that my previous question about libvte is right...which is strange since i've added vte as dependency in the deb package.
