### ISSUE TITLE
No symbol table is loaded.  Use the \"file\" command.

### ISSUE THREAD

**Issue by leh103** [BBasile/Coedit#299]
I have installed Coedit-3.6.7 using the linux64.setup file on both the Zorin OS and the Debian based version of Mint LInux lmde2. I get an "Access Violation" when ever I open the the Terminal window via both the menu and by clicking on the tab. And, I get no prompt in the Terminal. The default Terminal emulator on both is the Gnome-Terminal.

On I think a related issue, when installing from the linux64.deb file it appears to install correctly, but crashes when open with an abort error message.

This really is not that important as I can just open the Terminal from the file manager and use it, but I thought you'd like to know.

**Comment by leh103** [comment]
I must admit that I am use to debugging on Windows with Visual Studio, where compiling debug and then debugging just always works. Although, I have been using Linux for awhile, I have just now starting coding again using D language instead of C#,
When trying out one of the examples (pi.d) using Coedit with the GDB commander I get this error-> No symbol table is loaded.  Use the \"file\" command.
In Windows the symbol table gets generated automatically when you do I debug compile.
What do I have to due to get a symbol table in Coedit.

**Comment by BBasile** [comment]
xref #298

**Comment by BBasile** [comment]
BTW: you must compile with `-g`. So with Coedit, adds the shebang (it's used by the runnable modules in a special way) to the source

```
#!notused -g
```

And in GDB commander, use the popup associated to the "power" button to indicate that you wish to debug a runnable. The compile as a runnable.

See 
- http://bbasile.github.io/Coedit/features_runnables#shebang-line
- http://bbasile.github.io/Coedit/widgets_gdb_commander#toolbar

**Comment by BBasile** [comment]
In case it's a project (DUB) you must select a debug configuration in the project inspector.
If it's a project (CE) you must define manually a debug config and select it in the project inspector.
In both case: recompile then only launch the debugger.

For the runnables + GDB i had made [a video](https://www.youtube.com/watch?v=HbEPkA1EfaU&index=10&list=PLzk8A0LUvEOV-OMdz09jfOahwnKoA2na_&t=0s) a while back
