### ISSUE TITLE
Enums in symbol viewer, are not all listed

### ISSUE THREAD

**Issue by rikkimax** [BBasile/Coedit#3]
![capture](https://cloud.githubusercontent.com/assets/992755/11771786/f5843bc4-a279-11e5-811c-a219573d145f.PNG)

**Comment by BBasile** [comment]
Right, anonymous enums are not handled, will do.

**Comment by BBasile** [comment]
By the way the buttons in the _Messages_ widget look awefull on Windows 10. This doesn't look normal.
