### ISSUE TITLE
CoEdit requires an existing directory named "source" for dub projects.

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#300]
I was trying to have an empty global `sourcePaths` and define them in configurations instead, but I noticed that CoEdit would then print "List index (0) out of bounds" whenever I try to activate any but the first configuration. Creating an empty place-holder "source" directory fixes the error.

Example:
```JSON
{
  "name" : "my-app",
  "description" : "Description of app",
  "sourcePaths" : [],
  "importPaths" : [],
  "configurations" : [
    {
      "name" : "configA",
      "targetType" : "executable",
      "targetName" : "a_app",
      "sourcePaths" : [
        "a_source"
      ],
    },
    {
      "name" : "configB",
      "sourcePaths" : [
        "b_source"
      ],
    }
  ]
}
```

**Comment by BBasile** [comment]
I'm not able to reproduce the error. I've copied the json and put it in an empty folder. There's probably a detail missing in your description.

Which version do you use ?

**Comment by BBasile** [comment]
okay, the error happens when the folders are not empty

**Comment by mleise** [comment]
You mean, like "source" is empty, but the others are filled? Yes that's the setup. I should probably attach a little zip project next time.

**Comment by BBasile** [comment]
No i meant when the folder "b_source" or "b_source" is not empty.
By the way i just found that the issue happens when sources dont have a module declaration, which means that in theory the problem can be avoided by adding `module <name>;` to each source.
