### ISSUE TITLE
Still can't install using the deb package

### ISSUE THREAD

**Issue by leh103** [BBasile/Coedit#301]
I have both libvte9 and libvte2.9.0 but I am unable to install libvte2.9.1 due to dependency issues. I assume that you used the one I can't install as a dependency since I still can't install it using the deb installer because of a dependency on vte.

However, I did install version 3.6.8 using the setup file and the terminal works, so thanks for fixing it.

**Comment by BBasile** [comment]
what is the name of the package providing _libvte.so.9_ (or ultimatly _libvte.so_) ? Historically i've always used RPM-based distribs...

**Comment by BBasile** [comment]
Now that the bug is fixed i could remove the dependency or set is optional.

**Comment by BBasile** [comment]
If i understand correctly the problem is caused by a broken dependency graph on your system so i close.
