### ISSUE TITLE
WordEndRight cannot be set to Ctrl+Right.

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#306]
I prefer to use Ctrl+Right and Ctrl+Left to move the caret to the end or start of a word respectively, so I tried to swap the shortcuts for WordEnd and WordEndRight, but WordEndRight is always unbound after closing the IDE (reading "shortcut (none)")

**Comment by BBasile** [comment]
I agree. personaly i like more when ctrl+arrow makes the cursor goes to edge always.

**Comment by BBasile** [comment]
I'll change the default shortcut in next patch. I cant count how many times i've use ctrl+left just after ctrl+right because of this.

**Comment by BBasile** [comment]
Sorry i was biased because of something else i made in a UI library. It's actually a bug. In first place i thought you'd like that ctrl+right to go to word begin, word end, word begin, word end. etc

**Comment by mleise** [comment]
Well that option could be explored as well. :-)
