### ISSUE TITLE
Assigning F3 to "JumpToDeclaration" does not work

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#312]
What the title says. I removed F3 as shortcut for "Find next" and reassigned it to "JumpToDeclaration". Restarting Coedit does not help. The shortcut property pane shows that F3 is assigned to "JumpToDeclaration" but it does nothing in the editor. Right-click on the symbol and choosing the action manually from the menu works though.

**Comment by BBasile** [comment]
It's completely broken. i also tried with F2 and the old action is still triggered (rename identifier).

**Comment by mleise** [comment]
Lol, don't worry, I've just tried a JSON test suite on my JSON parser and it found so many bugs that I am in for a rewrite of some parts. Recursion limit? Nope. Crash. Unclosed string at the end, deadlock. And minor compliance issues that will slow parsing down for no apparent gain, but what don't you do to achieve 100% compliance. As soon as someone else uses your code in a way you are not used to, things start falling apart left and right.

**Comment by mleise** [comment]
Thanks! It is fixed now.

**Comment by BBasile** [comment]
> Lol, don't worry

Basic problem is that since i put my own shortcuts as default i barely tested them, so the problem you found was actually there for __years__.
