### ISSUE TITLE
F1 does not work, but DDoc and Jump to declaration work.

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#313]
DDoc pop-up:
![DDoc pop-up](https://user-images.githubusercontent.com/609447/39365482-857ccd02-4a31-11e8-85f1-29f1332efbea.png)

Jump to declaration shows "/opt/dmd-2.078/import/std/file.d":
![Jump to declaration](https://user-images.githubusercontent.com/609447/39365621-ed2b7962-4a31-11e8-87ef-241788511966.png)

And the paths are set accordingly:
![Compiler paths](https://user-images.githubusercontent.com/609447/39365682-1df960ea-4a32-11e8-9b98-d6d48e0df934.png)

Yet, when pressing F1 on `dirEntries`:
![F1](https://user-images.githubusercontent.com/609447/39365930-d1c7d84a-4a32-11e8-9c97-b0de7c2b1852.png)

What is causing this? (I'm using Coedit v3.6.9)

**Comment by BBasile** [comment]
Off topic but for GDC and LDC you just need to set one path for the library since the layout is different (it's the parent folder of the one containing both runtime and std) and left the second empty

**Comment by mleise** [comment]
phobosDocRoot = https://dlang.org/phobos/

**Comment by BBasile** [comment]
I see the problem on the screenshot. Put the caret in the middle of the identifier and it will work. Will see if i can fix this now because i gotta release 3.6.10 quite quickly.

**Comment by mleise** [comment]
The caret was in the middle of the identifier. The error message for non-existent identifiers is:

> The source where the symbol is declared is not existing.

While for errors finding the right help page it is:

> The source where the symbol is declared does not seem to be part of Phobos or the D runtime.

**Comment by BBasile** [comment]
Did you try the beta ? Actually i'm about to bump.

**Comment by BBasile** [comment]
is DCD managed by Coedit or do you launch it before, by hand.
Do DCD import paths use the DCD config file ?

Looking at the compiler paths the problem would be actually that they are not right.
runtime path should be some like  here : http://bbasile.github.io/Coedit/options_compilers_paths

**Comment by BBasile** [comment]
Other possible source of problem is that the location provided is browsed back and it only succeeds if at some point the folder name is "phobos" or "core". If your setup is non standard then it explains the problem.

See the logic here: https://github.com/BBasile/Coedit/blob/962980ed142dc9d2463fa4a53f1d219001509824/src/ce_synmemo.pas#L1949-L1962

**Comment by BBasile** [comment]
I see, it doesn't work because the "std" folder is not in a "phobos" folder. I can stop the loop on "std" an it will work.

**Comment by mleise** [comment]
Sorry, I used to bother Alex while he was working on Mono-D. Then he said he is done studying and will stop developing Mono-D, so I turned to the next best D IDE to bother its developer with bug reports. The shortcut fixes will certainly help other users, too. So thanks for the new release. Will install it asap on Linux and Windows.
