### ISSUE TITLE
Tab switching only works once

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#314]
Hi Basile, here is the first of the new batch of bug reports.

This one is about the common Ctrl+Tab flips through open tabs shortcut. I've assigned it to "select next page" and it works, but only once. This is because the editor needs to have the focus for "select next page" to work, and focus is lost after tabbing.
Ideally Ctrl+Tab could be used to flip through all open documents either from left to right or in last recently used order.

**Comment by BBasile** [comment]
I've noticed this issue a while ago and managed to make it works always using ALT+numpad 4 (previouspage ) and ALT+numpad 6 (next page). Then it works always. There's something with TAB that doesn't work for these 2 actions.
