### ISSUE TITLE
Shortcut options remembers filter keyword, but doesn't filter

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#315]
The following screen shots illustrate the bug. When you filter for a key ...
![keyword set and filtered](https://user-images.githubusercontent.com/609447/39487081-5c4812e8-4d7e-11e8-942e-6fe19826453a.png)
... and then leave the options window and come back later, the filter text is still set, but the list of shortcuts is not filtered:
![keyword still set](https://user-images.githubusercontent.com/609447/39487009-3d0fafee-4d7e-11e8-97a2-66d05cf1b017.png)
I don't mind it personally that the filter text is remembered, since it is one click to clear it.

**Comment by BBasile** [comment]
Yeah what's filtered is the shortcuts combination, not the action it triggers.
