### ISSUE TITLE
"the tool cannot be found" although the correct compiler path is provided

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#316]
I've set GDC's path to "/usr/x86_64-pc-linux-gnu/gcc-bin/6.4.0/gdc", which is correct, but the about dialog still shows "the tool cannot be found":
![about dialog](https://user-images.githubusercontent.com/609447/39487637-2fde82da-4d80-11e8-8fa0-771486a5110e.png)

**Comment by BBasile** [comment]
Yes this is because the dialog was created before adding the compiler paths, at a time where only compilers that could be found by the system were usable.
