### ISSUE TITLE
Dfmt commander window replaces source file with an error message

### ISSUE THREAD

**Issue by poliklosio** [BBasile/Coedit#32]
I have an open file with these contents:

```
struct Mystruct
{
    int helloVar = 9;
    this(int value)
    {
        value = 99;
        helloVar = value;
    }
};
```

Then, when I click Windows/Dfmt commander and then click "apply formatting" button, the contents of my file are changed to:
`Unrecognized option --template_constraint_style=conditional_newline_indent`

My platform: Windows 7, 64bit

**Comment by BBasile** [comment]
Is the dfmt binay up to date ? this option was added [the 18 jan 2016](https://github.com/Hackerpilot/dfmt/issues/215).

**Comment by poliklosio** [comment]
```
C:\D\dmd2\windows\bin>dfmt --version
0.4.5
```
I installed dfmt 3 days ago with
```
dub fetch dfmt
dub run dfmt
```

**Comment by BBasile** [comment]
The dub package is not upd to date. You should have `0.5.0`.

I recommend you to build using the git repository.

**Comment by poliklosio** [comment]
Just for the record, updating dfmt helped.

**Comment by BBasile** [comment]
The next version implements a system (78544f3e3a0a4f776c1a3840630272bd39f8583e) to prevent this kind of problem in the future.
