### ISSUE TITLE
settings are hard to find

### ISSUE THREAD

**Issue by poliklosio** [BBasile/Coedit#33]
This is an enhancement request.

When initially evaluating Coedit on Windows, I couldn't find the settings so I mistakingly thought that Coedit is in early stages of development, and therefore not necessarily usable. Only a bit later I found the settings by chance, called "Options editor" in the middle of the "Windows" dropdown.
A better placement would be one of:
* Next to the other dropdowns (so "File Edit Project Run Windows" would become "File Edit Project Run Windows Settings") or 
* As the last option in the "Edit" dropdown. 
* In the "File" dropdown.

**Comment by BBasile** [comment]
The way it appears in the window menu can't be changed but it can cerntainly be added to elsewhere.
