### ISSUE TITLE
Access violation error when compiling dub project

### ISSUE THREAD

**Issue by btbytes** [BBasile/Coedit#33]
![screen shot 2015-08-28 at 11 18 05 am](https://cloud.githubusercontent.com/assets/1047/9549951/9fdbffe8-4d76-11e5-8d48-03dcba3c1c46.png)

As you can see from the screenshot, i've followed the instructions under "Using DUB in Coedit as a project pre-build process" section of the documentation wiki. 

I have verified that `dub` exists and build the project successfully on the terminal.

What am i missing?

**Comment by BBasile** [comment]
I confirm the bug.
Come back in one hour on the release page. 
All the archives will be updated.

**Comment by BBasile** [comment]
All the archives are updated. 
Thx for the report.
