### ISSUE TITLE
Coedit appears to launch a lot of small windows when launched

### ISSUE THREAD

**Issue by poliklosio** [BBasile/Coedit#34]
See the screenshot. This happens for a fraction of a second (not long enough to even read whats on the individual windows), then Coedit is launched successfully.
Those windows look like something went wrong and is about to crash, or like some virus was launched in the background (could be interpreted as unrelated to launching Coedit).

![coedit](https://cloud.githubusercontent.com/assets/18385396/14478488/78a100e6-0116-11e6-9d06-b307e09d1be8.png)

**Comment by BBasile** [comment]
There is no problem here. The widgets are initialized before being docked. Usually it's so fast that no one should be able to capture a picture of this phase. However this can happen under circumstances (if you launch CE just after booting, if Intel speed step or any other dynamic clock modifier is enabled).

**Comment by poliklosio** [comment]
> Usually it's so fast that no one should be able to capture a picture of this phase.

It definitely takes about half a second for me every time.

**Comment by BBasile** [comment]
There's maybe a little something that could be done to hide the windows during init. Are you able to build Coedit ? Since this doesn't happen here I would need to know if the fix works.

**Comment by BBasile** [comment]
The fix is on master. If you can't test it you'll have to wait until next release, which is planned for soon (less than two weeks).

**Comment by poliklosio** [comment]
I built coedit out of curiosity. Unfortunately the issue is still there.

**Comment by BBasile** [comment]
Actually this is not a problem that depends on the machine, like said previously. I've verified that this also happens on a decent desktop computer under win7, stable clock, C1E deactivated, etc.

However I don't consider this issue as a bug. I'll maybe put on a note in the wiki.
