### ISSUE TITLE
Completions not fully working for string data type

### ISSUE THREAD

**Issue by srb623** [BBasile/Coedit#352]
If I have the following code fragment:

> import std.algorithm.iteration : filter, spliiter;

> string s = "a b c";

and I type in 's' and then '.' to see the autocompletion list, all I am seeing is the attributes for the string data type - I do not see splitter,  I I then put in, manually, the splitter details, I should be able to type in '.' and get 'filter' as an autocompletion - and I do not,

I have build Coedit and DCD from GIT and so have the latest versions.  I have configured DCD as per the readme and Coedit is configured as per the start up defaults,

Is the above an issue with my configuration (as I am new to D and Coedit) ?  
Is this a limitation of DCD ?
Is this an issue with your code ?

I am running Debian Linux, testing/buster on a 64 bit machine.

Any help would be much appreciated as this is the only frustration I have in what is otherwise an excellent IDE for D programming,

**Comment by BBasile** [comment]
> and I type in 's' and then '.' to see the autocompletion list, all I am seeing is the attributes for the string data type - I do not see splitter

What you want is UFCS completion, which is not handled by DCD, see https://github.com/dlang-community/DCD/issues/13

Someone started to work on this last summer but unfortunately didn't finish. UFCS requires to look at each free function present in the current module and in the imports which has a cost. Also even if it was implemented there is a problem with template parameters. Template constraints cant be evaluated by DCD (`splitter` for example has probably an overload that uses `if(isSomeString!T)` and DCD couldn't evaluate that).

> Any help would be much appreciated as this is the only frustration I have in what is otherwise an excellent IDE for D programming,

Thanks. Don't forget to put a star if you like it ;)
