### ISSUE TITLE
Adding directories of source files to a project adds every file type

### ISSUE THREAD

**Issue by mleise** [BBasile/Coedit#36]
It would be nice if the default was to include *.d and *.di. My personal preference are configurable source path items. Instead of a static list you add some of those to the project and set their path e.g. "${PROJECT_DIR}/../third_party/coolio/" and a filter "*.d;*.di". The relative directories allow the project to be moved to other computers or shared via source version control systems and the filter handles the addition/removal of source files automatically in case someone uses other tools to manage the source tree. Eclipse even goes so far as to allow you to add more path variables. This comes handy when a project needs some import path for an external lib, but this import path may vary from system to system. So you could add an import path to "${VIBED_IMPORT}/source" and everyone checking out the project defines this path variable in a per user configuration file next to the project file. What do you think?

**Comment by mleise** [comment]
Also when adding a directory (on Linux) it adds absolute paths. When saving and loading the native project file, it expects relative paths though and after giving it that it will ask for the location of every single file. After clicking yes, a file dialog pops up, but the requested file name isn't shown any more and if you forget it you may pick the wrong file.

**Comment by BBasile** [comment]
- When you click to add a directory of sources it adds only files that can be passed to dmd as it. So *.d, *.di, *.o, *.obj, *.a, *.lib, I've just checked.
- Sources paths are displayed as absolute only if the project is not yet saved. If it's not the case this can be a bug.

You can try to click _No_ in every dialog that proposes to patch the path then click Project, edit project file. Then edit the filenames in **Sources.Strings = ()**. Save the file and the project will be reloaded automatically.

**Comment by BBasile** [comment]
Yes there's a small bug: under linux when it saves absolute paths, the leading backslash is missing. That's why the dialogs are displayed won reopening. But the paths shouldn't be saved as absolute.

**Comment by mleise** [comment]
The confusion arises from the label "sources" paired with the action of quietly adding binaries that are probably the product of compiling said sources. Looking forward to the next version.

**Comment by BBasile** [comment]
CE projects handle objects and static libraries as source, on purpose. For example you can have a _*.o_ produced by GCC and its matching interface as _*.di_. It's up to the user to define the output path to _bin_ or another sub directory. This feature won't be removed because i use it. So the only bug is the backslash.

**Comment by BBasile** [comment]
The bug is actually that new relative path are extracted _after_ saving thus they are written only if a project is saved twice.
