### ISSUE TITLE
Can't compile from terminal

### ISSUE THREAD

**Issue by FFY00** [BBasile/Coedit#363]
Running `lazbuild` as instructed in https://bbasile.github.io/Coedit/build.html gives the following output:

```
Error: (lazarus) invalid Lazarus directory "": directory lcl not found
Error: (lazarus) Building failed: coedit.lpi
```

**Comment by BBasile** [comment]
It's probably your Lazarus setup that's not correct. Are you able to start the IDE and let's say compile a simple application ? (in Laz : Project -> New Project -> Application, then build, SHIFT+F9 by default)

**Comment by BBasile** [comment]
I left some more notes on IRC. The problem is not from the doc i believe. You can still get more help even if i close.
