### ISSUE TITLE
Unable to open the input method，Unable to input Chinese ，in Linux.

### ISSUE THREAD

**Issue by nufe** [BBasile/Coedit#366]
Unable to open the input method，Unable to input Chinese ，in Linux.!!!

**Comment by BBasile** [comment]
Sounds like a problem with the framework i use, i.e Lazarus but maybe more deeper e.g GTK2 and maybe even more deeper e.g XCB. Not sure i can do something for this.

**Comment by BBasile** [comment]
Please tell me when and where this happens. For now i don't even know if it's when the software is launched, when you type code or when you enter text in other controls. Also if you have some time to, you can [setup Lazarus 1.8.x](https://sourceforge.net/projects/lazarus/files/), create a simple application and see if the error happens too.

Lazarus applications are supposed to be unicode compatible out of the box.

**Comment by BBasile** [comment]
Also if any follower uses a non Latin alphabet, especially any of the CJK, i'd like to know if you ever had problems with Coedit ?

**Comment by BBasile** [comment]
please @nufe, provide the feedback i need (when, where, how in short). Also another Q: is Chinese the default input method ?

**Comment by BBasile** [comment]
for now without more info i close.
