### ISSUE TITLE
More options in the mini-explorer

### ISSUE THREAD

**Issue by rikkimax** [BBasile/Coedit#4]
The mini explorer window is practically useless as it does not allow (unless Coedit is default for file type) editing inside of Coedit.
Let alone renaming, moving and deleting.
It should also allow for syncing up to the currently open file.

**Comment by BBasile** [comment]
No it's useful. I use it all the time.

**Comment by rikkimax** [comment]
Ok, so if you click on the pencil icon for a selected file it opens in Coedit.
By default double click will open in Notepad++ for me.

**Comment by BBasile** [comment]
- double click or flash icon: open in the shell, either file or folder.
- pen icon: if the file is a project then close current one and open selected file a a project otherwise always open the file in a new code editor. When the file is not a _.d_ or not a _.di_, the "generic highlighter" is used.

**Comment by rikkimax** [comment]
This is one of those little things where double clicking is a requirement.
I'm ignoring tree view of directories and files not combined since that is a matter of taste and not really a loss in productivity.

Perhaps, an option to make double click = open in editor?
Also how about right click for renaming and deleting + drag and drop support for moving?
