### ISSUE TITLE
Known types should be highlighted

### ISSUE THREAD

**Issue by rikkimax** [BBasile/Coedit#5]
Type:
```D
alias sljit_ub = ubyte;
alias sljit_si = int;
```

Usage:
```D
sljit_ub get_jump_code(sljit_si type) {
```

``sljit_ub`` and ``sljit_si`` should both be highlighted since the types are known.
``string`` for example should not be hard coded, instead that should be determined from druntime. Currently it is highlighted as a keyword.

**Comment by BBasile** [comment]
CE highlighter is based on lexical analysis, not grammatical. Btw that 's why it's so fast, even on huge source.
