### ISSUE TITLE
View white space in editor

### ISSUE THREAD

**Issue by rikkimax** [BBasile/Coedit#7]
It can be a little annoying if you are use to seeing every character in a file e.g. space and tab. Optionally new line(\r not \n) to not have it. Again another option to enable feature for editor.

![capture](https://cloud.githubusercontent.com/assets/992755/11772050/08abc746-a27d-11e5-84ff-13a6ea3539ef.PNG)

**Comment by BBasile** [comment]
You can set the highlighter to show whites characters:

![whites_ce](https://cloud.githubusercontent.com/assets/16154339/11772577/14602d98-a21e-11e5-926c-7b24ebfb6baf.png)

Alternatively you can set the option _show special chars_:

![spec_ce](https://cloud.githubusercontent.com/assets/16154339/11772611/6081b75a-a21e-11e5-9460-47de93cb9599.png)

**Comment by rikkimax** [comment]
Ok, feature implemented just the settings dialog is just not easy to navigate.
