### ISSUE TITLE
Compiling on Mac OS X

### ISSUE THREAD

**Issue by btbytes** [BBasile/Coedit#7]
I have little familiarity with Lazarus, but I do have access to a mac and would like to see how far I can take this. So, this is the error I'm getting on compiling with lazbuild.

```
lazbuild -B coedit.lpi  
primary config path: /Users/pgowda/.lazarus
TLazPackageGraph.CheckIfCurPkgOutDirNeedsCompile Last= -Fu.  -MObjFPC -Scghi -O1 -g -gl -vewnhi -l fcllaz.pas
TLazPackageGraph.CheckIfCurPkgOutDirNeedsCompile Last= -Fu../../packager/units/i386-darwin;.  -MObjFPC -Scghi -O1 -g -gl -vewnhi -l lazutils.pas
TLazPackageGraph.CheckIfCurPkgOutDirNeedsCompile Last= -Fuforms;widgetset;nonwin32;../packager/units/i386-darwin;../components/lazutils/lib/i386-darwin;. -Fiinclude  -MObjFPC -Scghi -O1 -g -gl -vew -l alllclunits.pp
TLazPackageGraph.CheckIfCurPkgOutDirNeedsCompile Last= -MObjFPC -Scghi -O1 -g -gl -dcarbon -vewnhi -l -Fucarbon;carbon/objc;carbon/pascocoa/appkit;carbon/pascocoa/foundation;../../packager/units/i386-darwin;../../components/lazutils/lib/i386-darwin;../units/i386-darwin;. -Ficarbon;carbon/objc;carbon/pascocoa/appkit;carbon/pascocoa/foundation lcl.pas
TLazPackageGraph.CheckIfCurPkgOutDirNeedsCompile  Missing state file for AnchorDocking 0.6: /Developer/lazarus/components/anchordocking/lib/i386-darwin/AnchorDocking.compiled
[TExternalToolList.Run] CmdLine="/usr/local/bin/ppc386 -B  -MObjFPC -Scghi -O1 -g -gl -vewnhi -Fu/Developer/lazarus/packager/units/i386-darwin -Fu/Developer/lazarus/components/lazutils/lib/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin -Fu/Developer/lazarus/lcl/units/i386-darwin/carbon -Fu/Developer/lazarus/components/anchordocking/ -FU/Developer/lazarus/components/anchordocking/lib/i386-darwin/ -l -dLCL -dLCLcarbon anchordockpkg.pas" WorkDir="/Developer/lazarus/components/anchordocking/"
Hint: Start of reading config file /etc/fpc.cfg
Hint: End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 2.6.2 [2013/02/03] for i386
Copyright (c) 1993-2012 by Florian Klaempfl and others
Target OS: Darwin for i386
Compiling anchordockpkg.pas
Compiling anchordocking.pas
PPU Loading /Developer/lazarus/lcl/units/i386-darwin/lresources.ppu
PPU Source: lresources.pp not found
Recompiling LResources, checksum changed for System
anchordocking.pas(104,28) Fatal: Can't find unit LResources used by AnchorDocking
TExternalToolList.Run Exception: /Developer/lazarus/components/anchordocking/anchordocking.pas(104,28) Fatal: Can't find unit LResources used by AnchorDocking
ERROR: tool reported error
```

**Comment by BBasile** [comment]
The current error seems to be related to an outdated setup.

- FPC should be at least 2.6.4 and lazarus 1.4, so try to setup these version [this one] (http://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.4/)

- Optionally, once setup, try in a first time to open the IDE because Lazarus checks the compiler and library paths at startup (in a kind of wizard), si in case of error, you'll be notified.

recompile, you should have another error, related to one of the source file (ce_xxx.pas) and not a component. At this time you'll be able to look more closely at the plateform-specific incompatibilities.

**Comment by BBasile** [comment]
@btbytes, did you gave up ? maybe there's a misunderstanding ?
Anyway thx for the try.

**Comment by btbytes** [comment]
I did upgrade to the versions you mentioned.  

```shell
$ fpc -v
Free Pascal Compiler version 2.6.4 [2015/05/14] for x86_64
``` 

compilation still gives exact same error as reported before.

**Comment by BBasile** [comment]
http://forum.lazarus.freepascal.org/index.php?topic=28525.new#new

if nobody can help then i'll close and try to find an old mini Mac...

**Comment by btbytes** [comment]
I made some progress. 

I had to recompile lazarus, install Qt4Pas framework. Quite an adventure ;) 

I'm now able to reproduce the error outlined in the wiki. ie., 

```
ce_common.pas(916,32) Error: Identifier not found "internalAppIsRunning"
```

**Comment by btbytes** [comment]
Oh, i understand now, we need to define a new function specific to Mac OSX. I'll make an attempt at this...

**Comment by btbytes** [comment]
I got the project compiled with this: 
I have to iron out the `ps` bits because i'm not sure if this is doing the job. I'll get back to fixing this later in the day (hopefully).... 
```
{$IFDEF DARWIN}
function internalAppIsRunning(const ExeName: string): integer;
var
  proc: TProcess;
  lst: TStringList;
begin
  Result := 0;
  proc := tprocess.Create(nil);
  proc.Executable := 'ps';
  proc.Parameters.Add('| grep ');
  proc.Parameters.Add(ExeName);
  proc.Parameters.Add('| grep -v grep');
  proc.Options := [poUsePipes, poWaitonexit];
  try
    proc.Execute;
    lst := TStringList.Create;
    try
      lst.LoadFromStream(proc.Output);
      Result := Pos(ExeName, lst.Text);
    finally
      lst.Free;
    end;
  finally
    proc.Free;
  end;
end;
{$ENDIF} 
```

**Comment by BBasile** [comment]
Awesome, i follow this from near so don't esitate to contact me if you need further information. Basically you'll need to check every part that contains an `{$IFDEF WINDOWS}` or `{$IFDEF LINUX}`. Sometimes i think that it'll work by replacing `{$IFDEF LINUX}` by `{$IFDEF POSIX}`, but that's not sure.

**Comment by btbytes** [comment]
I have sent a pull request #8 that compiles. Takes a different approach to determining if the interalAppIsRunning.

**Comment by BBasile** [comment]
I've merged and verified. Actually, what's been written in my previous comment is wrong. For the remaining piece of codes surrounded with platform-specific switches, ` {$IFDEF LINUX}` could be replaced by  `{$IFDEF UNIX}`.

**Comment by timotheecour** [comment]
just read this superficially; does coedit work on OSX?

**Comment by btbytes** [comment]
yes. on my machine. YMMV.

**Comment by timotheecour** [comment]
then could https://github.com/BBasile/Coedit/blob/master/README.md be updated with:
multi platform (Windows, Linux) and OSX (YMMV/experimental/...).
That would make ppl using mac more likely to give it a try and report bugs etc ?

**Comment by BBasile** [comment]
I doubt that _master_ or _1_fixes_ ***work***. They can only be ***compiled***.

For example there are some exceptions defined here and there that will crash the program under OSX saying "_this has to be implemented_".

Also I'd like to say to any OSX D user with Object Pascal background, there is this doc to help if want to port:

https://gist.github.com/BBasile/bae24a536f2b390e5beb
