### ISSUE TITLE
Windows version fails to install

### ISSUE THREAD

**Issue by Tafnab** [BBasile/Coedit#70]
I installed this on one machine, but my home machine fails with the following error: "Windows cannot access the specified device, path, or file. You may not have permissions to access the item."

I have DMD installed and works. Running as administrator doesn't help. It's a fresh install of Windows 7 w/ DMD registered with Vis Studio 2013 community. I can use it on the linux box, but I also wanted it on Windows. Any help appreciated.

**Comment by BBasile** [comment]
I'll verify the installer later but in the meantime you can try to extract manually the files that are in the [zip that doesn't contain the "setup" suffix](https://github.com/BBasile/Coedit/releases/download/2_update_6/coedit.2update6.win32.zip).

**Comment by BBasile** [comment]
I've verified on 2 machines. Your report seems invalid, in both cases the installer worked. What you can do is try to reproduce the installer steps to see what happens. You can lloks at the sources:

https://github.com/BBasile/Coedit/blob/master/cesetup/cesetup.d#L89

The only thing that's a bit exotice is the way the shortcut is done:

https://github.com/BBasile/Coedit/blob/master/cesetup/cesetup.d#L316

So for now make a DMD program that reads the 3 environment variables and that creates a shortcut with a vbs.

**Comment by Tafnab** [comment]
It's Avast anti-virus software blocking access. It knows that this file came from elsewhere, and it just decided to go ahead and not let me know that it was blocking things. There's a whitelist (called exceptions) under customize active protection settings. That fixes it.

**Comment by BBasile** [comment]
Oh, yeah the antivirus. I gotta put a note about this in the wiki. In the past there's already been someone who reported a false positive detection from Norton A.V heuristic system.
