### ISSUE TITLE
Drag-n-drop windows are unstable on Linux

### ISSUE THREAD

**Issue by Tafnab** [BBasile/Coedit#73]
I like the default layout Coedit starts with, but if I attempt to move any of those windows, I can never get the default back. I end up with every window being full-width horizontal. Fortunately, you put the delete layout.xml trick into the instructions.

I'm on Linux Mint KDE 14.04. To me, it seems like the layout engine doesn't know it has three columns. I can see the blue boxes being occasionally anchored to a corner, but mostly horizontal full-width. Is there some sort of trick with this style of layout system? I didn't see anything in the instructions?

**Comment by BBasile** [comment]
To get several widgets on the same column you must drag to the top or to the bottom of a column.
To get a suplemental page in a column you must drag at the center of the column. 

The central area is a bit special and you can only get stuff docked at the bottom.

If you want the same docking as on the screenshot I can share my xml.

**Comment by BBasile** [comment]
You can watch this video if you don't understand how the docking is working. It's recorded after a full supression of the settings so it's like after a fresh installation.

https://vimeo.com/170816162

I close because obviously docking is working.
