### ISSUE TITLE
Formatting of D code

### ISSUE THREAD

**Issue by rikkimax** [BBasile/Coedit#8]
dfmt is a great little utility, would be great to have it supported like dcd.

**Comment by BBasile** [comment]
You can set it as a custom tools.

**Comment by rikkimax** [comment]
Like refactoring, this is just one of those little features that is just "expected" to be built in.

**Comment by BBasile** [comment]
Refactoring is not something that you'll be able to see in the near future. There is no grammatical analysis at all in CE.

**Comment by rikkimax** [comment]
I asked on IRC, but like me they swear there was a tool that could do refactoring, we couldn't find it however unfortunately.

**Comment by BBasile** [comment]
@rikkimax I've updated again the binaries (the Dfmt thing we've talked about on the NG...). Thx again, two bugs spotted and fixed.
