### ISSUE TITLE
What about mac support?

### ISSUE THREAD

**Issue by dossan** [BBasile/Coedit#9]
Do you intend to add support to Mac OS X?

**Comment by BBasile** [comment]
Send me a mini mac and I'll do it :wink:

This is almost that. I don't do it because I'm not a mac user at all. In theory there not much to do to port it, but so far nobody wanted to do it (neither in the D community nor in the Lazarus one).

**Comment by BBasile** [comment]
The problem is that it would be a long term collaboration. If I find someone for the OSX version, it's not just for a build. The person must be available when I want to release, without discussion.

**Comment by BBasile** [comment]
If you're clever enough to earn enough money to buy a mac you should be clever enough to port Coedit... :wink:
